### ISSUE TITLE
2 new issues :)

### ISSUE THREAD

**Issue by Llamrei80** [Valkyr-JS/ValkyrSceneCards#22]
Hey there,

found two new glitches.

First:
Sometimes the title is displayed under the description of a video.
![Bildschirmfoto_20240718_111614](https://github.com/user-attachments/assets/61d76226-11b4-4c27-a457-2f4121cf2c41)

Second:
When changing the number of lines to display in the description the whole description is shown.
![Bildschirmfoto_20240719_102344](https://github.com/user-attachments/assets/5991c518-f427-4358-a287-d31af41f2beb)
![Bildschirmfoto_20240719_102614](https://github.com/user-attachments/assets/8536c361-12dd-4d5c-bb8e-3f895910380d)
This happens only sometimes.

**Comment by Valkyr-JS** [comment]
Hey, really sorry for the late response on this.

I'm afraid I can't duplicate either of these issues. If it happens again, would you be able to take a screenshot of any errors in the console (F12 in Google), and also copy the code black for the scene card? That should help me see what's going on.

Thanks, and my apologies again.
