### ISSUE TITLE
Performer Gender and Numbers

### ISSUE THREAD

**Issue by Ho2ho** [Valkyr-JS/ValkyrSceneCards#26]
Hello,

Thank you for this neat plugin.. really appreciate the efforts you put into it.

I have two suggestions to enhance the user experience for performers:

 1- It would be beneficial to have an option to filter the list to display only female performers. 

 2- Additionally, limiting the number of performers displayed to a maximum of five, with an ellipsis to indicate additional performers, could help declutter the interface, especially in scenes with a large number of participants.

Thank you for considering this feedback.

**Comment by Valkyr-JS** [comment]
Hey

Thanks for the kind words! Two solid suggestions, I'll definitely incorporate them, hopefully soon.

Thanks
