### ISSUE TITLE
Enhancement: Filesize/FPS Options

### ISSUE THREAD

**Issue by coderdudeo** [Valkyr-JS/ValkyrSceneCards#27]
First off, I love your redesign of scene cards! It makes the viewing experience so much better in my experience. The only things that would make it perfect for me is if it also showed the filesize and the FPS somewhere. Idk if that would make it too cluttered, but it's kind of nice when trying to organize duplicate scenes. 

Would be a nice to have but not necessary as there are currently other plugins that show those two stats and yours is easy to toggle on/off. Anyways, thank you again for your contribution!

**Comment by Valkyr-JS** [comment]
Great ideas, thanks. I've added and they'll be available shortly in the next release.
