### ISSUE TITLE
[Scene Cards] Getting SQL errors in log

### ISSUE THREAD

**Issue by Llamrei80** [Valkyr-JS/ValkyrSceneCards#4]
Getting those errors when Scene Cards 0.2 and performer avatars is enabled:

`findImages: input: findImages error querying aggregate fields: executing query: SELECT COUNT(DISTINCT temp.id) as total, COALESCE(SUM(temp.megapixels), 0) / 1000000 as megapixels, SUM(temp.size) as size FROM (SELECT DISTINCT images.id, COALESCE(image_files.width, 0) * COALESCE(image_files.height, 0) as megapixels, COALESCE(files.size, 0) as size FROM images LEFT JOIN (
		SELECT j.*, d.column1 AS root_id, d.column2 AS item_id FROM images_tags AS j
		INNER JOIN (VALUES(, )) AS d ON j.tag_id = d.column2
	)
	 AS image_tag ON image_tag.image_id = images.id LEFT JOIN performers_images AS performers_join ON performers_join.image_id = images.id LEFT JOIN images_files ON images_files.image_id = images.id LEFT JOIN image_files ON images_files.file_id = image_files.file_id LEFT JOIN files ON images_files.file_id = files.id WHERE ((image_tag.root_id IS NOT NULL) AND (performers_join.performer_id IN (?)))) as temp [[233]]: error executing `SELECT COUNT(DISTINCT temp.id) as total, COALESCE(SUM(temp.megapixels), 0) / 1000000 as megapixels, SUM(temp.size) as size FROM (SELECT DISTINCT images.id, COALESCE(image_files.width, 0) * COALESCE(image_files.height, 0) as megapixels, COALESCE(files.size, 0) as size FROM images LEFT JOIN (
		SELECT j.*, d.column1 AS root_id, d.column2 AS item_id FROM images_tags AS j
		INNER JOIN (VALUES(, )) AS d ON j.tag_id = d.column2
	)
	 AS image_tag ON image_tag.image_id = images.id LEFT JOIN performers_images AS performers_join ON performers_join.image_id = images.id LEFT JOIN images_files ON images_files.image_id = images.id LEFT JOIN image_files ON images_files.file_id = image_files.file_id LEFT JOIN files ON images_files.file_id = files.id WHERE ((image_tag.root_id IS NOT NULL) AND (performers_join.performer_id IN (?)))) as temp` [[233]]: near ",": syntax error`

It doesn't matter if the option Use profile images as default avatars is enabled or not. Enabling avatars causes the error messages to apear.
Everything seems to work but errors make me uncomfortable.

**Comment by Valkyr-JS** [comment]
Hey, can you give me all your settings for the plugin? Also, what other plugins do you have installed and enabled? Looks like it could be conflicting with something.

**Comment by Llamrei80** [comment]
![Screenshot 2024-07-11 152836](https://github.com/Valkyr-JS/ValkyrSceneCards/assets/30364330/b25a6472-1e90-4767-9c72-1c0229f4a4a5)

To test if it's conflicting I disabled every other plugin and custom CSS. Still getting those errors.

**Comment by Valkyr-JS** [comment]
Ok, I've been able to duplicate it now. It only seems to be happening when I navigate to my homepage but not my scenes page, though I think that's likely down to what data is being queried.

My guess is that it's logging an error when it can't find matching data. I'll take a better look this evening and see if I can put a fix together to handle the error more gracefully.

**Comment by Valkyr-JS** [comment]
Should be fixed in the latest version. You may need to click "Refresh plugins" then hard refresh your browser before checking again, but the errors don't log for me now.

The cause was custom avatars were still being searched for even if no associated tag ID was provided, causing a corrupted query. Custom avatars are now only searched for if a tag ID has been provided.
